name: pytorch91
channels:
- pytorch
- defaults
dependencies:
- bleach=2.1.2=py36_0
- bokeh=0.12.14=py36_0
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2018.1.18=py36_0
- cffi=1.11.4=py36h9745a5d_0
- click=6.7=py36h5253387_0
- cloudpickle=0.5.2=py36_1
- cycler=0.10.0=py36h93f1223_0
- dask=0.17.1=py36_0
- dask-core=0.17.1=py36_0
- dbus=1.12.2=hc3f9b76_1
- decorator=4.2.1=py36_0
- distributed=1.21.1=py36_0
- entrypoints=0.2.3=py36h1aec115_2
- expat=2.2.5=he0dffb1_0
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=hab7d2ae_1
- glib=2.53.6=h5d9569c_2
- gmp=6.1.2=h6c8ec71_1
- gst-plugins-base=1.12.4=h33fb286_0
- gstreamer=1.12.4=hb53b477_0
- heapdict=1.0.0=py36_2
- html5lib=1.0.1=py36h2f9c1c0_0
- icu=58.2=h9c2bf20_1
- imageio=2.2.0=py36he555465_0
- intel-openmp=2018.0.0=hc7b2577_8
- ipykernel=4.8.2=py36_0
- ipython=6.2.1=py36h88c514a_1
- ipython_genutils=0.2.0=py36hb52b0d5_0
- ipywidgets=7.1.2=py36_0
- jedi=0.11.1=py36_0
- jinja2=2.10=py36ha16c418_0
- jpeg=9b=h024ee3a_2
- jsonschema=2.6.0=py36h006f8b5_0
- jupyter=1.0.0=py36_4
- jupyter_client=5.2.2=py36_0
- jupyter_console=5.2.0=py36he59e554_1
- jupyter_core=4.4.0=py36h7c827e3_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libpng=1.6.34=hb9fc6fc_0
- libsodium=1.0.15=hf101ebd_0
- libstdcxx-ng=7.2.0=h7a57d05_2
- libtiff=4.0.9=h28f6b97_0
- libxcb=1.12=hcd93eb1_4
- libxml2=2.9.7=h26e45fe_0
- locket=0.2.0=py36h787c0ad_1
- markupsafe=1.0=py36hd9260cd_1
- matplotlib=2.1.2=py36h0e671d2_0
- mistune=0.8.3=py36_0
- mkl=2018.0.1=h19d6760_4
- msgpack-python=0.5.5=py36h6bb024c_0
- nbconvert=5.3.1=py36hb41ffb7_0
- nbformat=4.4.0=py36h31c9010_0
- ncurses=6.0=h9df7e31_2
- networkx=2.1=py36_0
- notebook=5.4.0=py36_0
- numpy=1.14.0=py36h3dfced4_1
- olefile=0.45.1=py36_0
- openssl=1.0.2n=hb7f436b_0
- packaging=16.8=py36ha668100_1
- pandas=0.22.0=py36hf484d3e_0
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py36ha6701b7_1
- parso=0.1.1=py36h35f843b_0
- partd=0.3.8=py36h36fd896_0
- pcre=8.41=hc27e229_1
- pexpect=4.4.0=py36_0
- pickleshare=0.7.4=py36h63277f8_0
- pillow=5.0.0=py36h3deb7b8_0
- pip=9.0.1=py36h6c6f9ce_4
- prompt_toolkit=1.0.15=py36h17d85b1_0
- psutil=5.4.3=py36h14c3975_0
- ptyprocess=0.5.2=py36h69acd42_0
- pycparser=2.18=py36hf9f622e_1
- pygments=2.2.0=py36h0d3125c_0
- pyparsing=2.2.0=py36hee85983_1
- pyqt=5.6.0=py36h0386399_5
- python=3.6.4=hc3d631a_1
- python-dateutil=2.6.1=py36h88d3b88_1
- pytz=2018.3=py36_0
- pywavelets=0.5.2=py36he602eb0_0
- pyyaml=3.12=py36hafb9ca4_1
- pyzmq=16.0.3=py36he2533c7_0
- qt=5.6.2=hd25b39d_14
- qtconsole=4.3.1=py36h8f73b5b_0
- readline=7.0=ha6073c6_4
- scikit-image=0.13.1=py36h14c3975_1
- scipy=1.0.0=py36hbf646e7_0
- send2trash=1.5.0=py36_0
- setuptools=38.4.0=py36_0
- simplegeneric=0.8.1=py36_2
- sip=4.18.1=py36h51ed4ed_2
- six=1.11.0=py36h372c433_1
- sortedcontainers=1.5.9=py36_0
- sqlite=3.22.0=h1bed415_0
- tblib=1.3.2=py36h34cf8b6_0
- terminado=0.8.1=py36_1
- testpath=0.3.1=py36h8cadb63_0
- tk=8.6.7=hc745277_3
- toolz=0.9.0=py36_0
- tornado=4.5.3=py36_0
- traitlets=4.3.2=py36h674d592_0
- wcwidth=0.1.7=py36hdf4376a_0
- webencodings=0.5.1=py36h800622e_1
- wheel=0.30.0=py36hfd4bba0_1
- widgetsnbextension=3.1.4=py36_0
- xz=5.2.3=h55aa19d_2
- yaml=0.1.7=had09818_2
- zeromq=4.2.2=hbedb6e5_2
- zict=0.1.3=py36h3a3bf81_0
- zlib=1.2.11=ha838bed_2
- cuda91=1.0=h4c16780_0
- pytorch=0.3.1=py36_cuda9.1.85_cudnn7.0.5_2
- torchvision=0.2.0=py36h17b6947_1
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - openexr==1.3.0
  - prompt-toolkit==1.0.15
  - torch==0.3.1.post2
prefix: /home/mark/anaconda3/envs/pytorch91

